drop table if exists lecture;
drop table if exists note;
create table if not exists lecture (
    id bigint generated by default as identity,
    name varchar(255),
    lectureTitle varchar(255),
    body varchar(255),
    primary key (id)
);
create table if not exists note (
    id uuid default random_uuid() not null,
    filename varchar(255),
    content_type varchar(255),
    content blob,
    lecture_id bigint,
    primary key (id),
    foreign key (lecture_id) references lecture(id)
    );

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    fullName varchar(255),
    email varchar(255),
    phone varchar(255),
    PRIMARY KEY (username)
    );
CREATE TABLE IF NOT EXISTS user_roles (
    user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
    );

drop table if exists comment;
CREATE TABLE IF NOT EXISTS comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    context VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE,
    lecture_id BIGINT NOT NULL,
    poll_id BIGINT NOT NULL,
    FOREIGN KEY (lecture_id) REFERENCES lecture(id) ON DELETE CASCADE,
    FOREIGN KEY (username) REFERENCES users(username),
    FOREIGN KEY (poll_id) REFERENCES poll(id) ON DELETE CASCADE
    );

drop table if exists poll;
drop table if exists vote;
CREATE TABLE IF NOT EXISTS poll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacherName VARCHAR(255) NOT NULL,
    question VARCHAR(255) NOT NULL,
    optionAText VARCHAR(255) NOT NULL,
    optionBText VARCHAR(255) NOT NULL,
    optionCText VARCHAR(255) NOT NULL,
    optionDText VARCHAR(255) NOT NULL,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS vote (
    id uuid default random_uuid() not null,
    username VARCHAR(255) NOT NULL,
    poll_id BIGINT NOT NULL,
    choice VARCHAR(255) NOT NULL,
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE,
    FOREIGN KEY (poll_id) REFERENCES poll(id) ON DELETE CASCADE
)